schema_version: "0.3"
extends:
  - ../presets/taibei_ue.yaml

scene:
  id: taibei_ue
  title: "Taipei UE release"

runtime:
  backup_output_before_run: true
  backup_previous_packages: false
  backup_self_if_exists: false
  backup_dir: backups
  backup_exclude:
    - "**/*.zip"
    - "*.zip"

pipeline:
  - step: resolve_extent
    enabled: true

  - step: terrain
    enabled: true
    depends_on: [resolve_extent]

  - step: osm_city_usd
    enabled: true

  - step: osm_labels
    enabled: true

  - step: nav_pgm
    enabled: true

  - step: overlay
    enabled: true

  - step: assemble_world
    enabled: true

  - step: package_zip
    enabled: true
    depends_on: [assemble_world]
