#!/usr/bin/env python3
"""Build occupancy PGM at a chosen resolution into a sibling folder.

Does not replace the package default nav2/connected/ or rewrite World/alignment.
Uses the same OSM polygon logic as the nav_pgm pipeline step.

Usage:
  python tools/build_nav_pgm_at_resolution.py \\
    --package output/ScenePackages/taibei_ue_20260831 \\
    --config configs/nav_pgm_osm_only_3m.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from cityusd.nav2_paths import NAV2_CONNECTED
from cityusd.nav_polys import collect_nav_polygons  # noqa: E402
from cityusd.osm_parse import parse_osm  # noqa: E402
from cityusd.pgm import rasterize_pgm  # noqa: E402
from cityusd.pipeline.terrain import load_extent_context  # noqa: E402


def _find_osm(package_dir: Path) -> Path:
    staging = package_dir / "inputs" / "build_data" / "osm"
    if staging.is_dir():
        for ext in ("*.osm.pbf", "*.osm"):
            hits = sorted(staging.glob(ext))
            if hits:
                return hits[0]
    raise FileNotFoundError(f"No staged OSM under {staging}")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--package", type=Path, required=True, help="Existing Scene Package dir")
    p.add_argument(
        "--config",
        type=Path,
        default=None,
        help="nav_pgm JSON (default: configs/nav_pgm_osm_only_3m.json)",
    )
    p.add_argument(
        "--resolution-m",
        type=float,
        default=None,
        help="Override config resolution_m",
    )
    args = p.parse_args(argv)

    package_dir = args.package.resolve()
    if not package_dir.is_dir():
        print(f"ERROR: package not found: {package_dir}", file=sys.stderr)
        return 1

    root = _TOOLS.parent
    cfg_path = (args.config or (root / "configs" / "nav_pgm_osm_only_3m.json")).resolve()
    step_cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    if args.resolution_m is not None:
        step_cfg["resolution_m"] = float(args.resolution_m)

    resolution_m = float(step_cfg.get("resolution_m", 3.0))
    outputs = step_cfg.get("outputs") or {}
    layer_flags = step_cfg.get("layers") or {}

    map_pgm = package_dir / str(outputs.get("map_pgm", f"nav2/variants/{resolution_m:g}m/map.pgm"))
    map_yaml = package_dir / str(outputs.get("map_yaml", map_pgm.parent / "map.yaml"))
    map_meta = package_dir / str(outputs.get("meta_json", map_pgm.parent / "map_meta.json"))

    if map_pgm.resolve().parent == (package_dir / NAV2_CONNECTED).resolve():
        print("ERROR: refusing to write into nav2/connected/ — change outputs in config", file=sys.stderr)
        return 2

    _, origin, extent = load_extent_context(package_dir)
    osm_path = _find_osm(package_dir)
    print(f"[build_nav_pgm] package={package_dir.name}")
    print(f"[build_nav_pgm] osm={osm_path.name} resolution_m={resolution_m}")
    print(f"[build_nav_pgm] → {map_pgm.relative_to(package_dir).as_posix()}")

    osm = parse_osm(osm_path, origin)
    occupied, free = collect_nav_polygons(
        osm,
        use_buildings=bool(layer_flags.get("buildings", True)),
        use_water=bool(layer_flags.get("water", True)),
        use_roads_free=bool(layer_flags.get("roads", True)),
        simple_buildings=bool(step_cfg.get("simple_buildings", False)),
    )

    rasterize_pgm(
        extent,
        occupied,
        free,
        resolution_m,
        map_pgm,
        map_yaml,
        map_meta,
        origin,
        range_source=f"sibling_osm_{resolution_m:g}m",
    )

    note = map_pgm.parent / "README.txt"
    note.write_text(
        f"Sibling occupancy grid at {resolution_m} m/px.\n"
        f"Generated by tools/build_nav_pgm_at_resolution.py from {cfg_path.name}.\n"
        "Default package nav2/connected/ was not modified.\n",
        encoding="utf-8",
    )

    snap = map_pgm.parent / "nav_pgm.resolved.json"
    snap.write_text(json.dumps(step_cfg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    meta = json.loads(map_meta.read_text(encoding="utf-8"))
    print("[build_nav_pgm] OK")
    print(f"  size_px: {meta.get('size_px')}")
    print(f"  resolution_m: {meta.get('resolution_m')}")
    print(f"  map: {map_pgm}")
    print(f"  yaml: {map_yaml}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
