#!/usr/bin/env python3
"""Build a connectivity-focused nav PGM (converter-style, scene-aligned).

Writes to nav2/connected/ by default (pipeline v0.3 equivalent).

Usage:
  python tools/build_nav_connected_pgm.py \\
    --package <USD package dir>
"""
# 中文说明：在已有包上单独写出连通型 map.pgm 套件（默认 NAV2_CONNECTED）。

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

from cityusd.nav2_paths import NAV2_CONNECTED
from cityusd.nav_polys import collect_nav_polygons_connected  # noqa: E402
from cityusd.osm_parse import parse_osm  # noqa: E402
from cityusd.pgm import FREE, OCCUPIED, UNKNOWN, rasterize_pgm, write_nav2_yaml_bundle  # noqa: E402
from cityusd.pipeline.terrain import load_extent_context  # noqa: E402


def _find_osm(package_dir: Path) -> Path:
    """功能：在包内 staging 目录查找 OSM 数据。"""
    staging = package_dir / "inputs" / "build_data" / "osm"
    for ext in ("*.osm.pbf", "*.osm"):
        hits = sorted(staging.glob(ext))
        if hits:
            return hits[0]
    raise FileNotFoundError(f"No OSM under {staging}")


def process(
    package_dir: Path,
    out_dir: Path,
    *,
    resolution_m: float,
    simple_buildings: bool,
) -> dict:
    """功能：解析 OSM、栅格化连通占据图并写 yaml/meta。

    返回：
        含分辨率、多边形数量等元信息的字典。
    """
    extent_payload, origin, extent = load_extent_context(package_dir)
    osm = parse_osm(_find_osm(package_dir), origin)
    occupied, free = collect_nav_polygons_connected(
        osm,
        simple_buildings=simple_buildings,
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    map_pgm = out_dir / "map.pgm"
    map_local_yaml = out_dir / "map_local.yaml"
    map_meta = out_dir / "map_meta.json"

    # free_all_touched：道路缓冲触及的像素均标自由，利于连通
    rasterize_pgm(
        extent,
        occupied,
        free,
        resolution_m,
        map_pgm,
        map_local_yaml,
        map_meta,
        origin,
        "connected_osm",
        free_all_touched=True,
        binary_occupancy=True,
        cost_same_as_map=True,
    )

    write_nav2_yaml_bundle(
        out_dir,
        extent=extent,
        extent_payload=extent_payload,
        origin=origin,
        resolution_m=resolution_m,
        scene_id=package_dir.name,
    )

    note = {
        "mode": "connected",
        "resolution_m": resolution_m,
        "free_all_touched": True,
        "binary_occupancy": True,
        "road_source": "motor_carriageway_polygons (flat cap, round join, no hierarchy cut)",
        "occupied_polys": len(occupied),
        "free_polys": len(free),
    }
    (out_dir / "nav_connected_meta.json").write_text(
        json.dumps(note, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out_dir / "README.txt").write_text(
        "Connectivity-focused nav PGM (nav2/connected).\n"
        "No unknown(205); flat-cap road buffers; free uses all_touched.\n"
        "Same origin/extent as scene package for USD alignment.\n"
        "Generated by tools/build_nav_connected_pgm.py\n",
        encoding="utf-8",
    )
    return note


def main(argv: list[str] | None = None) -> int:
    """功能：命令行入口。返回 0 成功，2 拒绝覆盖旧版 nav/。"""
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--package", type=Path, required=True, help="Existing Scene Package with extent.json + staged OSM")
    p.add_argument(
        "--output",
        type=Path,
        default=None,
        help=f"Output nav dir (default: <package>/{NAV2_CONNECTED})",
    )
    p.add_argument("--resolution-m", type=float, default=1.0)
    p.add_argument("--simple-buildings", action="store_true")
    args = p.parse_args(argv)

    package_dir = args.package.resolve()
    out_dir = (args.output or (package_dir / NAV2_CONNECTED)).resolve()
    legacy_nav = (package_dir / "nav").resolve()
    if out_dir.resolve() == legacy_nav:
        print("error: refuse to overwrite legacy nav/", file=sys.stderr)
        return 2

    meta = process(
        package_dir,
        out_dir,
        resolution_m=float(args.resolution_m),
        simple_buildings=bool(args.simple_buildings),
    )

    import numpy as np

    raw = (out_dir / "map.pgm").read_bytes()
    i = newlines = 0
    while i < len(raw) and newlines < 3:
        if raw[i] == 10:
            newlines += 1
        i += 1
    lines = [ln for ln in raw[:i].decode().splitlines() if ln and not ln.startswith("#")]
    w, h = map(int, lines[1].split())
    g = np.frombuffer(raw[i:], np.uint8).reshape(h, w)
    print("build_nav_connected_pgm OK")
    print(f"  output: {out_dir}")
    print(f"  shape: [{w}, {h}] resolution_m: {meta['resolution_m']}")
    print(f"  free(254): {int((g == FREE).sum())} occ(0): {int((g == OCCUPIED).sum())} unk(205): {int((g == UNKNOWN).sum())}")
    print(f"  free_polys: {meta['free_polys']} occupied_polys: {meta['occupied_polys']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
