#!/usr/bin/env python3
"""Post-process a city occupancy PGM: keep only roads free.

Does not modify the Scene Package pipeline. Reads an existing nav2/connected/map.pgm (or other variant)
(and optional cost.pgm / map.yaml) and writes to nav2/variants/:

Usage:
  python tools/remap_pgm_roads_only.py \\
    --input <…/connected> \\
    --output <…/variants/roads_only>
"""
# 中文说明：仅保留 FREE(254) 为可通行，写出旁路目录，不改主产物。

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import numpy as np

FREE = 254
OCCUPIED = 0
COST_FREE = 0
COST_LETHAL = 254


def read_pgm(path: Path) -> tuple[bytes, np.ndarray]:
    """Read binary P5 PGM; return (header_bytes, grid).

    功能：读取二进制 P5 PGM，返回原始文件头与二维栅格。
    """
    raw = path.read_bytes()
    if not raw.startswith(b"P5"):
        raise ValueError(f"not a binary PGM P5: {path}")
    i = 0
    newlines = 0
    # Skip magic + width/height/maxval lines (three newlines)
    while i < len(raw) and newlines < 3:
        if raw[i] == 10:
            newlines += 1
        i += 1
    header = raw[:i]
    lines = [
        ln
        for ln in header.decode("ascii", errors="replace").splitlines()
        if ln and not ln.startswith("#")
    ]
    if len(lines) < 3 or lines[0] != "P5":
        raise ValueError(f"unrecognized PGM header in {path}: {lines[:4]!r}")
    w, h = map(int, lines[1].split())
    maxval = int(lines[2])
    if maxval != 255:
        raise ValueError(f"expected maxval 255, got {maxval} in {path}")
    data = np.frombuffer(raw[i:], dtype=np.uint8)
    expected = w * h
    if data.size != expected:
        raise ValueError(f"{path}: pixel count {data.size} != {w}*{h}={expected}")
    return header, data.reshape(h, w).copy()


def write_pgm(path: Path, header: bytes, grid: np.ndarray) -> None:
    """Write PGM using original header size and new pixel payload.

    功能：用原文件头尺寸写出 PGM。
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(header + np.ascontiguousarray(grid, dtype=np.uint8).tobytes())


def remap_roads_only(grid: np.ndarray) -> np.ndarray:
    """Keep FREE pixels; force everything else to OCCUPIED.

    功能：仅 FREE 保持可通行，其余（含 unknown 205）一律占用。
    """
    return np.where(grid == FREE, FREE, OCCUPIED).astype(np.uint8)


def occupancy_to_cost_binary(grid: np.ndarray) -> np.ndarray:
    """Map free→0, else lethal 254.

    功能：占据图转二值代价图。
    """
    return np.where(grid == FREE, COST_FREE, COST_LETHAL).astype(np.uint8)


def process(nav_dir: Path, out_dir: Path) -> dict:
    """Process a nav directory into a roads-only sibling folder.

    功能：处理整个 nav 目录并写出 roads-only 变体。
    """
    src_map = nav_dir / "map.pgm"
    if not src_map.is_file():
        raise FileNotFoundError(f"missing {src_map}")

    header, grid = read_pgm(src_map)
    n_free_in = int(np.count_nonzero(grid == FREE))
    n_unk_in = int(np.count_nonzero(grid == 205))
    n_occ_in = int(np.count_nonzero(grid == OCCUPIED))

    out = remap_roads_only(grid)
    n_free_out = int(np.count_nonzero(out == FREE))
    n_occ_out = int(np.count_nonzero(out == OCCUPIED))

    out_dir.mkdir(parents=True, exist_ok=True)
    write_pgm(out_dir / "map.pgm", header, out)
    write_pgm(out_dir / "cost.pgm", header, occupancy_to_cost_binary(out))

    src_yaml = nav_dir / "map.yaml"
    if src_yaml.is_file():
        # Keep origin/resolution/thresholds; image name stays map.pgm
        shutil.copy2(src_yaml, out_dir / "map.yaml")

    src_meta = nav_dir / "map_meta.json"
    if src_meta.is_file():
        shutil.copy2(src_meta, out_dir / "map_meta.json")

    note = out_dir / "README_roads_only.txt"
    note.write_text(
        "Post-processed occupancy: only OSM road pixels (254) are free;\n"
        "all other pixels (including former unknown/gray 205) are occupied (0).\n"
        "Generated by tools/remap_pgm_roads_only.py — pipeline code unchanged.\n",
        encoding="utf-8",
    )

    return {
        "input": str(src_map),
        "output_dir": str(out_dir),
        "shape": list(out.shape),
        "in_free_254": n_free_in,
        "in_unknown_205": n_unk_in,
        "in_occupied_0": n_occ_in,
        "out_free_254": n_free_out,
        "out_occupied_0": n_occ_out,
    }


def main(argv: list[str] | None = None) -> int:
    """CLI entry. Returns 2 if output would overwrite input.

    功能：命令行入口。
    """
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Existing nav directory containing map.pgm",
    )
    p.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output directory (created; does not overwrite --input)",
    )
    args = p.parse_args(argv)

    nav_dir = args.input.resolve()
    out_dir = args.output.resolve()
    if out_dir == nav_dir:
        print("error: --output must differ from --input (refusing overwrite)", file=sys.stderr)
        return 2

    stats = process(nav_dir, out_dir)
    print("remap_pgm_roads_only OK")
    for k, v in stats.items():
        print(f"  {k}: {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
